// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHvwLszWn-uXRgW89DTYHOddBLK4shdN8',
    appId: '1:439486351486:android:8b6456abfdb549c982f02f',
    messagingSenderId: '439486351486',
    projectId: 'technik-fruit-basket',
    storageBucket: 'technik-fruit-basket.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo2rIahWc375q4k0Xkyu6dcnKcwEoREaU',
    appId: '1:439486351486:ios:0c68e5e066d5a37b82f02f',
    messagingSenderId: '439486351486',
    projectId: 'technik-fruit-basket',
    storageBucket: 'technik-fruit-basket.appspot.com',
    iosClientId: '439486351486-vm3vsc22380ke2j16hodrpeg2kg6nkh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitBasket',
  );
}
